/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Cliente;

import DataDados.Dados;
import DataDados.Dados.Action;
import Server.Jogo;
import Server.ServidorSocket;
import java.awt.Color;
import java.net.InetAddress;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Jhonatan Santos
 */
public class ClienteServidor_Tela extends javax.swing.JFrame {

    private static ClienteServidor_Tela clienteServidor_Tela = null;

    //Metodo Sengleton
    public static ClienteServidor_Tela get() {
        if (clienteServidor_Tela == null) {
            clienteServidor_Tela = new ClienteServidor_Tela();
        }
        return clienteServidor_Tela;
    }

    public ClienteServidor_Tela() {
        initComponents();
        setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jListJogadores = new javax.swing.JList<>();
        jPanel3 = new javax.swing.JPanel();
        jTextFieldIp = new javax.swing.JTextField();
        jButtonConectar = new javax.swing.JButton();
        jLabelStatus2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jButtonIniciar = new javax.swing.JButton();
        jLabelIp = new javax.swing.JLabel();
        jLabelStatus = new javax.swing.JLabel();
        jButtonPronto = new javax.swing.JButton();
        jLabelInfo = new javax.swing.JLabel();
        jRadioButtonCriar = new javax.swing.JRadioButton();
        jRadioButtonConectar = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Batalha Naval Senai");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Configuraçoes do Servidor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Jogadores", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jListJogadores.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jListJogadores);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jTextFieldIp.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldIp.setText("127.0.0.1");
        jTextFieldIp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Endereço de IP", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jButtonConectar.setBackground(new java.awt.Color(15, 219, 57));
        jButtonConectar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonConectar.setText("Conectar");
        jButtonConectar.setEnabled(false);
        jButtonConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConectarActionPerformed(evt);
            }
        });

        jLabelStatus2.setBackground(new java.awt.Color(255, 255, 255));
        jLabelStatus2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelStatus2.setForeground(new java.awt.Color(255, 0, 0));
        jLabelStatus2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStatus2.setText("Desconectado");
        jLabelStatus2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Status", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jTextFieldIp, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabelStatus2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonConectar)
                .addGap(80, 80, 80))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabelStatus2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jTextFieldIp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonConectar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButtonIniciar.setBackground(new java.awt.Color(33, 208, 11));
        jButtonIniciar.setForeground(new java.awt.Color(0, 0, 0));
        jButtonIniciar.setText("Iniciar");
        jButtonIniciar.setEnabled(false);
        jButtonIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIniciarActionPerformed(evt);
            }
        });

        jLabelIp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelIp.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Endereço do Servidor", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jLabelStatus.setBackground(new java.awt.Color(255, 255, 255));
        jLabelStatus.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelStatus.setForeground(new java.awt.Color(255, 0, 0));
        jLabelStatus.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelStatus.setText("Offline");
        jLabelStatus.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Status", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabelIp, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE))
                    .addComponent(jLabelStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(0, 7, Short.MAX_VALUE)
                        .addComponent(jButtonIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabelIp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelStatus)
                .addContainerGap())
        );

        jButtonPronto.setBackground(new java.awt.Color(93, 230, 20));
        jButtonPronto.setText("Pronto");
        jButtonPronto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProntoActionPerformed(evt);
            }
        });

        jLabelInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Informações", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        jRadioButtonCriar.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButtonCriar);
        jRadioButtonCriar.setText("Iniciar Servidor");
        jRadioButtonCriar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonCriarActionPerformed(evt);
            }
        });

        jRadioButtonConectar.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroup1.add(jRadioButtonConectar);
        jRadioButtonConectar.setText("Conectar no Servidor ");
        jRadioButtonConectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonConectarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jRadioButtonConectar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonPronto, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButtonCriar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jRadioButtonConectar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButtonCriar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPronto, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConectarActionPerformed
        try {
            //Informações do Jogador para Envio ao Servidor
            ClienteServidor.get().iniciarConexao(jTextFieldIp.getText());
            Dados jogador = new Dados();
            jogador.setAction(Action.CONECTAR);
            jogador.setNome(ClienteDados.get().getNome());
            ClienteServidor.get().setConectar(jogador);
            //Menu Personalizado
            jButtonConectar.setText("Cancelar");
            jButtonConectar.setBackground(Color.RED);
            jLabelStatus2.setText("Online");
            jLabelStatus2.setForeground(Color.GREEN);
            jLabelInfo.setText("Conectado com Servidor!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possivel conectar ao servidor!", "Erro ao conectar", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonConectarActionPerformed

    private void jButtonIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIniciarActionPerformed
        try {
            //Iniciando Servidor
            ServidorSocket.get().iniciar();
            Jogo.getJogo().iniciarJogo(ClienteDados.get().getQtdLinhas(), ClienteDados.get().getQtdColunas());
            jLabelIp.setText(InetAddress.getLocalHost().getHostAddress());
            //Informações de Conexão
            ClienteServidor.get().iniciarConexao(String.valueOf(ClienteDados.get().getIp()));
            Dados jogador = new Dados();
            jogador.setAction(Action.CONECTAR);
            jogador.setNome(ClienteDados.get().getNome());
            ClienteServidor.get().setConectar(jogador);
            //Menu Personalizado
            jButtonIniciar.setText("Cancelar");
            jButtonIniciar.setBackground(Color.RED);
            jLabelStatus.setText("Online");
            jLabelStatus.setForeground(Color.GREEN);
            jLabelInfo.setText("Servidor foi Iniciado!");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Não foi possivel iniciar ao servidor!", "Erro ao criar o servidor", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_jButtonIniciarActionPerformed

    private void jRadioButtonConectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonConectarActionPerformed
        jButtonIniciar.setEnabled(false);
        jButtonConectar.setEnabled(true);
    }//GEN-LAST:event_jRadioButtonConectarActionPerformed

    private void jRadioButtonCriarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonCriarActionPerformed
        jButtonIniciar.setEnabled(true);
        jButtonConectar.setEnabled(false);
    }//GEN-LAST:event_jRadioButtonCriarActionPerformed

    private void jButtonProntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProntoActionPerformed
        Dados jogador = new Dados();
        jogador.setId(ClienteDados.get().getId());
        jogador.setsStart(true);
        jogador.setAction(Action.SSTART);
        ClienteServidor.get().setStartJogo(jogador);
        jLabelInfo.setText("Aguardando Jogadores!");
        jButtonPronto.setText("Aguardando");
        jButtonPronto.setBackground(Color.ORANGE);
    }//GEN-LAST:event_jButtonProntoActionPerformed

    public void atualizarListJogadores(){
        String[] jogadores = new String[ClienteDados.get().getListJogadores().size()];
        for(int i=0;i<ClienteDados.get().getListJogadores().size();i++){
            jogadores[i] = ClienteDados.get().getListJogadores().get(i);
            jogadores[i]+=ClienteDados.get().getStatusJogadores().get(i);
        }
        jListJogadores.setListData(jogadores);
    }
    public void iniciarJogo(){
        ClienteJogo_Tela.get().setVisible(true);
        setVisible(false);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButtonConectar;
    private javax.swing.JButton jButtonIniciar;
    private javax.swing.JButton jButtonPronto;
    private javax.swing.JLabel jLabelInfo;
    private javax.swing.JLabel jLabelIp;
    private javax.swing.JLabel jLabelStatus;
    private javax.swing.JLabel jLabelStatus2;
    private javax.swing.JList<String> jListJogadores;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jRadioButtonConectar;
    private javax.swing.JRadioButton jRadioButtonCriar;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldIp;
    // End of variables declaration//GEN-END:variables
}
